substitutions:
  # EC circuit, who's address is 100
  addEC: "100"
  update_ec: "60s"
  update_button_ec: "60s"

  sorting_group_ec: '31'

web_server:
  sorting_groups:
    - id: sorting_group_ec
      name: "Salinité - EZO"
      sorting_weight: ${sorting_group_ec}

api:
  actions: 
    - action: ec_change_address
      variables:
        address: int
      then:
        - lambda: |-
            id(ec_ezo).send_custom("I2C,{{address}}");
    - action: ec_custom_command
      variables:
        command: string
      then:
        - lambda: |-
            id(ec_ezo).send_custom({{command}});
    - action: ec_read_continous
      then:
      - repeat:
          count: 60
          then:
          - button.press: read_ec
          - delay: 1s
    - action: ec_calibrate_dry
      then:
      - lambda: |-
          id(ec_ezo).send_custom("Cal,dry");
    - action: ec_calibrate_low_12880
      then:
      - lambda: |-
          id(ec_ezo).send_custom("Cal,low,12880");
    - action: ec_calibrate_high_80000
      then:
      - lambda: |-
          id(ec_ezo).send_custom("Cal,high,80000");
    - action: ec_output_all_parameters
      then:
      - lambda: |-      
          id(ec_ezo).send_custom("O,EC,1");
          id(ec_ezo).send_custom("O,TDS,1");
          id(ec_ezo).send_custom("O,S,1");
          id(ec_ezo).send_custom("O,SG,1");

    # - action: ec_calibrate_custom
    #   variables:
    #     value: int
    #   then:
    #   - lambda: |-
    #       id(ec_ezo).send_custom(Cal,value);
    # - action: ezo_ec_custom_command
    #   variables:
    #     command: string
    #   then:
    #     - lambda: |-
    #         id(ec_ezo).send_custom('{{ command }}');
          
esphome:
    on_boot: 
        priority: 800
        then:
          - button.press: read_ec
          - button.press: send_selected_ec

interval:
  # Update Raw EC
  - interval: "${update_button_ec}"
    then:
      - button.press: read_ec

sensor:
  # EZO Circuits (SCL/RX, SDA/TX)
  # EZO Circuit - EC
  # Conductivity
  - platform: ezo
    icon: mdi:shaker-outline
    name: "Conductivité"
    id: ec_ezo
    address: ${addEC}
    unit_of_measurement: "mS/cm"
    accuracy_decimals: 2
    update_interval: "${update_ec}"
    state_class: "measurement"
    device_class: "volatile_organic_compounds_parts"
    filters:
      - lambda:
          return (x / 1000);
    web_server:
      sorting_group_id: sorting_group_ec
      sorting_weight: 13
    on_custom: 
      then:
        - lambda: 
            id(raw_value_ec).publish_state(x);
    on_calibration: 
      then:
        - lambda: 
            id(result_ec).publish_state(x);
    on_device_information: 
      then:
        - lambda: 
            id(result_ec).publish_state(x);

  # # Conductivity
  # - platform: template
  #   name: Conductivity
  #   id: sensor_conductivity
  #   icon: mdi:lightning-bolt-outline
  #   unit_of_measurement: "uS/cm"
  #   accuracy_decimals: 0
  #   update_interval: "${update_ec}"
  #   state_class: "measurement"
  #   lambda: |-
  #     std::string str = id(raw_value_ec).state;
  #     std::vector<std::string> v;
  #     char * token;
  #     char seps[] = ",";
  #     token = strtok (&str[0],seps);
  #     while (token != NULL) {
  #       v.push_back(token);
  #       token = strtok (NULL, seps);
  #     }
  #     if (v.size() == 4) {
  #       return std::stof(v[0]);
  #     } 
  #     else {
  #       return NULL;
  #     }

  # TDS
  - platform: template
    name: TDS
    id: sensor_tds
    unit_of_measurement: "g/L"
    icon: mdi:water-opacity
    accuracy_decimals: 2
    disabled_by_default: true
    update_interval: "${update_ec}"
    state_class: "measurement"
    device_class: "volatile_organic_compounds_parts"
    lambda: |-
      std::string str = id(raw_value_ec).state;
      std::vector<std::string> v;
      char * token;
      char seps[] = ",";
      token = strtok (&str[0],seps);
      while (token != NULL) {
        v.push_back(token);
        token = strtok (NULL, seps);
      }
      if (v.size() == 4) {
        return (std::stof(v[1]) / 1000);
      } 
      else {
        return NAN;
      }
    web_server:
      sorting_group_id: sorting_group_ec
      sorting_weight: 14

  # Salinity
  - platform: template
    name: Salinité
    id: sensor_salinity
    icon: mdi:shaker-outline
    unit_of_measurement: "ppt"
    accuracy_decimals: 2
    update_interval: "${update_ec}"
    state_class: "measurement"
    device_class: "volatile_organic_compounds_parts"
    lambda: |-
      std::string str = id(raw_value_ec).state;
      std::vector<std::string> v;
      char * token;
      char seps[] = ",";
      token = strtok (&str[0],seps);
      while (token != NULL) {
        v.push_back(token);
        token = strtok (NULL, seps);
      }
      if (v.size() == 4) {
        return std::stof(v[2]);
      } 
      else {
        return NAN;
      }
    web_server:
      sorting_group_id: sorting_group_ec
      sorting_weight: 10

  # Specific Gravity
  - platform: template
    name: Specific Gravity
    id: sensor_specific_gravity
    icon: mdi:cup-water
    unit_of_measurement: ""
    accuracy_decimals: 3
    update_interval: "${update_ec}"
    state_class: "measurement"
    device_class: "volatile_organic_compounds_parts"
    lambda: |-
      std::string str = id(raw_value_ec).state;
      std::vector<std::string> v;
      char * token;
      char seps[] = ",";
      token = strtok (&str[0],seps);
      while (token != NULL) {
        v.push_back(token);
        token = strtok (NULL, seps);
      }
      if (v.size() == 4) {
        return std::stof(v[3]);
      } 
      else {
        return NAN;
      }
    web_server:
      sorting_group_id: sorting_group_ec
      sorting_weight: 11

text_sensor:
  # Conductivity Raw Value
  - platform: template
    name: EC - Valeur brute
    id: raw_value_ec
    icon: mdi:counter
    # disabled_by_default: true
    on_value: 
      then:
        - component.update: ec_ezo
        - component.update: sensor_salinity
        # - component.update: sensor_conductivity
        - component.update: sensor_tds
        - component.update: sensor_specific_gravity
    web_server:
      sorting_group_id: sorting_group_ec

  # Selected Command Result - Conductivity
  - platform: template
    name: EC - Valeur Cmd
    icon: mdi:data-matrix
    id: result_ec
    # disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_ec

button:
  # Read Conductivity Probe
  - platform: template
    name: EC - Lire
    icon: mdi:read
    id: read_ec
    entity_category: "Config"
    # disabled_by_default: true
    on_press:
      then:
        - lambda: |-
            byte error;
            Wire.beginTransmission(${addEC});
            error = Wire.endTransmission();
            if (error == 0) {
              id(ec_ezo).send_custom("R");
            }
            else {
              ESP_LOGW("custom_conductivity_read", "No Conductivity sensor detected at address: ${addEC}!");
            }
    web_server:
      sorting_group_id: sorting_group_ec

  # Send Selected EZO Command - Conductitivy
  - platform: template
    name: EC - Envoi Cmd
    icon: mdi:apple-keyboard-command
    id: send_selected_ec
    entity_category: "Config"
    # disabled_by_default: true
    on_press:
      then:
        - lambda: |-
            const auto option = id(select_command_ec).current_option();
            if (option.has_value() && option.value() == "Lire") {
              id(ec_ezo).send_custom("R");
            }
            if (option.has_value() && option.value() == "Information") {
              id(ec_ezo).get_device_information();
            }
            if (option.has_value() && option.value() == "Status") {
              id(ec_ezo).send_custom("Status");
            }
            if (option.has_value() && option.value() == "Obt Val K") {
              id(ec_ezo).send_custom("K,?");
            }  
            if (option.has_value() && option.value() == "Obt val TDS") {
              id(ec_ezo).send_custom("TDS,?");
            }
            if (option.has_value() && option.value() == "Conv en NaCl - 0.48") {
              id(ec_ezo).send_custom("TDS,0.48");
            }
            if (option.has_value() && option.value() == "Obt parametre") {
              id(ec_ezo).send_custom("O,?");
            }  
            if (option.has_value() && option.value() == "Selct sonde K1") {
              id(ec_ezo).send_custom("K,1");
            }
            if (option.has_value() && option.value() == "Sortie Val Toutes (default)") {
              id(ec_ezo).send_custom("O,EC,1");
              id(ec_ezo).send_custom("O,TDS,1");
              id(ec_ezo).send_custom("O,S,1");
              id(ec_ezo).send_custom("O,SG,1");
            }
            if (option.has_value() && option.value() == "Unité - Conductivité") {
              id(ec_ezo).send_custom("O,EC,1");
              id(ec_ezo).send_custom("O,TDS,0");
              id(ec_ezo).send_custom("O,S,0");
              id(ec_ezo).send_custom("O,SG,0");
            }
            if (option.has_value() && option.value() == "Unité - Salinity") {
              id(ec_ezo).send_custom("O,EC,0");
              id(ec_ezo).send_custom("O,TDS,0");
              id(ec_ezo).send_custom("O,S,1");
              id(ec_ezo).send_custom("O,SG,0");
            }
            if (option.has_value() && option.value() == "Unité - Specific Gravity") {
              id(ec_ezo).send_custom("O,EC,0");
              id(ec_ezo).send_custom("O,TDS,0");
              id(ec_ezo).send_custom("O,S,0");
              id(ec_ezo).send_custom("O,SG,1");
            }
            if (option.has_value() && option.value() == "Unité - TDS") {
              id(ec_ezo).send_custom("O,EC,0");
              id(ec_ezo).send_custom("O,TDS,1");
              id(ec_ezo).send_custom("O,S,0");
              id(ec_ezo).send_custom("O,SG,0");
            }
            if (option.has_value() && option.value() == "Vérif Calibration") {
              id(ec_ezo).get_calibration();
            }  
            if (option.has_value() && option.value() == "Calibration @ SEC") {
              id(ec_ezo).send_custom("Cal,dry");
            }
            if (option.has_value() && option.value() == "Calibration @ BASSE = 12880") {
              id(ec_ezo).send_custom("Cal,low,12880");
            }
            if (option.has_value() && option.value() == "Calibration @ HAUTE = 80000") {
              id(ec_ezo).send_custom("Cal,high,80000");
            }
            if (option.has_value() && option.value() == "Calibration CLEAR") {
              id(ec_ezo).clear_calibration();
            }
            if (option.has_value() && option.value() == "Réinitialisation") {
              id(ec_ezo).send_custom("Factory");
            }
            // else {
            //   id(ec_ezo).send_custom("R");
            // }
    web_server:
      sorting_group_id: sorting_group_ec

select:
  - platform: template
    name: EC - Cmd Selectionnée
    id: select_command_ec
    icon: mdi:apple-keyboard-command
    # disabled_by_default: true
    optimistic: true
    entity_category: "Config"
    options:
      - "Lire"
      - "Information"
      - "Status"
      - "Réinitialisation"
      - "Obt Val K"
      - "Obt val TDS"
      - "Conv en NaCl - 0.48"
      - "Obt parametre"
      - "Selct sonde K1"
      - "Sortie Val Toutes (default)"
      - "Unité - Conductivité"
      - "Unité - Salinité"
      - "Unité - Specific Gravity"
      - "Unité - TDS"
      - "Vérif Calibration"
      - "Calibration @ SEC"
      - "Calibration @ BASSE = 12880"
      - "Calibration @ HAUTE = 80000"
      - "Calibration CLEAR"
    initial_option: "Vérif Calibration"
    set_action:
      - logger.log:
          format: "Chosen option: %s"
          args: ["x.c_str()"]
    web_server:
      sorting_group_id: sorting_group_ec
