substitutions:
  addORP: "98"  # Adresse I2C du circuit ORP (Oxidation-Reduction Potential)
  update_orp: "60s"  # Intervalle de mise à jour des valeurs ORP
  sorting_group_orp: '33'  # Poids pour trier le groupe ORP dans l'interface web

web_server:
  sorting_groups:
    - id: sorting_group_orp  # Groupe des capteurs ORP
      name: "ORP - EZO"  # Nom affiché du groupe ORP
      sorting_weight: ${sorting_group_orp}  # Poids de tri du groupe ORP

api:
  actions: 
    - action: orp_change_address  # Changer l'adresse I2C du capteur ORP
      variables:
        address: int
      then:
        - lambda: |-
            id(orp_ezo).send_custom("I2C,{{address}}");
    - action: orp_custom_command  # Envoi d'une commande personnalisée au capteur ORP
      variables:
        command: string
      then:
        - lambda: |-
            id(orp_ezo).send_custom({{command}});
    - action: orp_read_continous  # Lecture continue de la sonde ORP pendant 60 secondes
      then:
        - repeat:
            count: 60
            then:
              - button.press: read_orp
              - delay: 1s
    - action: orp_calibrate_225  # Calibration du capteur ORP à 225 mV
      then:
        - lambda: |-
            id(orp_ezo).send_custom("Cal,225");

esphome:
  on_boot:  # Actions exécutées au démarrage
    priority: 800
    then:
      - button.press: send_selected_orp

sensor:
  - platform: ezo  # Capteur ORP EZO
    icon: mdi:react
    name: "ORP"
    id: orp_ezo
    address: ${addORP}
    unit_of_measurement: "mV"
    accuracy_decimals: 1
    update_interval: "${update_orp}"
    state_class: "measurement"
    device_class: "voltage"
    web_server:
      sorting_group_id: sorting_group_orp
      sorting_weight: 10

text_sensor:
  - platform: template  # Résultat des commandes envoyées à la sonde ORP
    name: ORP - Valeur Cmd
    icon: mdi:data-matrix
    id: result_orp
    web_server:
      sorting_group_id: sorting_group_orp

button:
  - platform: template  # Bouton pour déclencher la lecture du capteur ORP
    name: ORP - Lire
    id: read_orp
    icon: mdi:read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            byte error;
            Wire.beginTransmission(${addORP});
            error = Wire.endTransmission();
            if (error == 0) {
              id(orp_ezo).send_custom("R");
            } else {
              ESP_LOGW("custom_orp_read", "No ORP sensor detected at address: ${addORP}!!");
            }
    web_server:
      sorting_group_id: sorting_group_orp
  - platform: template
    name: ORP - Envoi Cmd
    id: send_selected_orp
    icon: mdi:apple-keyboard-command
    entity_category: "Config"
    # disabled_by_default: true
    on_press:
      then:
        - lambda: |-
            const auto option = id(select_command_orp).current_option();
            if (option.has_value() && option.value() == "Lire") {
              id(orp_ezo).send_custom("R");
            }
            // Get Device Firmware Version
            if (option.has_value() && option.value() == "Information") {
              id(orp_ezo).get_device_information();
            }
            if (option.has_value() && option.value() == "Status") {
              id(orp_ezo).send_custom("Status");
            }
            if (option.has_value() && option.value() == "Vérif calibration") {
              id(orp_ezo).get_calibration();
            }  
            if (option.has_value() && option.value() == "Calibration @ 225 mV ") {
              id(orp_ezo).send_custom("Cal,225");
            }
            if (option.has_value() && option.value() == "Supr Calibration") {
              id(orp_ezo).clear_calibration();
            }
            // else {
            //   id(orp_ezo).send_custom("R");
            // }
    web_server:
      sorting_group_id: sorting_group_orp
  - platform: template
    name: "Appliquer nouvelle adresse ORP"  # Bouton pour appliquer le changement
    icon: mdi:network-outline
    id: orp_change_address_button
    on_press:
      then:
        - lambda: |-
            int addr = (int) id(new_orp_address).state;
            id(orp_ezo).send_custom("I2C," + to_string(addr));  // Envoie la commande de changement d'adresse
        - logger.log:
            format: "Changement d'adresse ORP demandé vers: %d"
            args: ["(int) id(new_orp_address).state"]
    web_server:
      sorting_group_id: sorting_group_orp  # Groupe visuel dans l'interface web

select:
  - platform: template
    name: ORP - Command Selectionnée
    id: select_command_orp
    optimistic: true
    icon: mdi:apple-keyboard-command
    # disabled_by_default: true
    entity_category: "Config"
    options:
      - "Lire"
      - "Information"
      - "Status"
      - "Vérif calibration"
      - "Calibration @ 225 mV "
      - "Supr Calibration"
    initial_option: "Vérif calibration"
    set_action:
      - logger.log:
          format: "Chosen option: %s"
          args: ["x.c_str()"]
    web_server:
      sorting_group_id: sorting_group_orp

number:
  - platform: template
    name: "Changer adresse ORP"  # Champ pour saisir une nouvelle adresse I2C
    id: new_orp_address
    min_value: 1
    max_value: 127
    step: 1
    initial_value: 98  # Adresse actuelle par défaut (0x62)
    mode: box
    optimistic: true
    entity_category: "Config"
    web_server:
      sorting_group_id: sorting_group_orp  # Groupe visuel dans l'interface web
