substitutions:
  ota_update_interval: 6h  # Vérification toutes les 6 heures

http_request:
  verify_ssl: false  # Désactive la vérification SSL pour éviter les erreurs sur GitHub

update:
  - platform: rest  # Utilisation de REST pour récupérer la version du firmware
    name: "reefmonitor Firmware Update"
    id: update_firmware_sensor
    entity_category: "diagnostic"
    update_interval: ${ota_update_interval}
    icon: mdi:update
    resource: https://raw.githubusercontent.com/Twinsen68/reefmonitor/firmware/reefmonitor.manifest.json
    json_attributes:
      - version  # Récupère la version du firmware disponible

button:
  - platform: template
    id: update_firmware
    name: "Mettre à jour reefmonitor Firmware - Stable"
    entity_category: "config"
    icon: mdi:update
    disabled_by_default: true
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.md5
            url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.bin
  