substitutions:
  ota_update_interval: 6h  # Intervalle entre les vérifications des mises à jour OTA

ota:
  - platform: http_request  # Utilisation des requêtes HTTP pour les mises à jour OTA

http_request:
  verify_ssl: false  # Désactivation de la vérification SSL pour les requêtes HTTP

update:
  - platform: http_request  # Plateforme permettant les mises à jour OTA par HTTP
    name: reefmonitor Firmware Update
    id: update_firmware_sensor
    entity_category: 'diagnostic'
    update_interval: ${ota_update_interval}  # Intervalle de vérification défini dans les substitutions
    icon: mdi:update
    source: https://raw.githubusercontent.com/Twinsen68/reefmonitor/firmware/reefmonitor.manifest.json  # URL du fichier manifest indiquant les versions disponibles
    web_server:
      sorting_group_id: sorting_group_diagnostic  # Assigner au groupe Diagnostic dans l'interface web

button:
  - platform: template  # Bouton pour lancer manuellement la mise à jour OTA
    id: update_firmware
    name: Update reefmonitor Firmware - Stable
    entity_category: "config"
    icon: mdi:update
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_config  # Assigner au groupe Configuration dans l'interface web
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.md5  # URL du fichier MD5 pour vérifier l'intégrité du firmware
            url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.bin  # URL du firmware binaire OTA à flasher
