substitutions:
  ota_update_interval: 6h

ota:
  - platform: http_request

http_request:
  verify_ssl: false

update:
  - platform: http_request
    name: AquaPi Firmware Update
    id: update_firmware_sensor
    entity_category: 'diagnostic'
    update_interval: ${ota_update_interval}
    icon: mdi:update
    source: https://raw.githubusercontent.com/Twinsen68/reefmonitor/firmware/aquapi.manifest.json
    web_server:
      sorting_group_id: sorting_group_diagnostic
button:
  - platform: template
    id: update_firmware
    name: Update AquaPi Firmware - Stable
    entity_category: "config"
    icon: mdi:update
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_config
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.md5  # URL pour vérifier la somme MD5 du firmware.
            url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.bin  # URL pour télécharger et flasher le firmware OTA.
