substitutions:
  update_firmware_sensor_interval: 6h  # Intervalle pour vérifier les mises à jour de firmware (6 heures).

ota:
  - platform: http_request

http_request:
  verify_ssl: false  # Désactive la vérification SSL pour les connexions HTTPS.


# update:
#   - platform: http_request
#     name: reefmonitor Firmware Update
#     update_interval: "${update_firmware_sensor_interval}"
#     id: update_firmware_sensor
#     entity_category: 'diagnostic'
#     icon: mdi:update
#     source: https://raw.githubusercontent.com/Twinsen68/raph/gh-pages/manifest.json

button:
  - platform: template
    id: update_firmware  # Identifiant unique pour ce bouton.
    name: Update reefmonitor Firmware - Releaseed (Experimental - ESP32)  # Nom affiché dans Home Assistant.
    entity_category: "config"  # Catégorie de configuration dans Home Assistant.
    icon: mdi:update  # Icône utilisée pour représenter les mises à jour.
    # disabled_by_default: true  # Peut être activé/désactivé selon les besoins.
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.md5  # URL pour vérifier la somme MD5 du firmware.
            url: https://raw.githubusercontent.com/Twinsen68/reefmonitor/main/bin/ota/reefmonitor-esp32.ota.bin  # URL pour télécharger et flasher le firmware OTA.
