substitutions:
  # names
  name: "Reefmonitor"
  friendly_name: "Reefmonitor"
  comment: "Reefmonitor ESP32 - Aquarium Controller & Monitor"
  project_name: "Twinsen68.Reefmonitor"
  sorting_group_name: "Reefmonitor "
  import: "false"

dashboard_import:
  package_import_url: github://Twinsen68/Reefmonitor/Reefmonitor_config.yaml@main
  import_full_config: "${import}"
      
text_sensor: 
  # Reefmonitor Version
  - platform: template
    name: "Reefmonitor Version"
    id: Reefmonitor_version
    icon: mdi:update
    update_interval: '365days'
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    update_interval: '365days'
    lambda: |-
      return {"github.com/Twinsen68/Reefmonitor"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic