substitutions:
  name: "Reefmonitor"  # Nom technique de l'appareil
  friendly_name: "Reefmonitor"  # Nom convivial affiché à l'utilisateur
  logger: "DEBUG"  # Niveau de journalisation (DEBUG, INFO, etc.)

  # Définition des broches utilisées
  opticalLowPin: "32"  # Broche capteur optique niveau bas (jaune)
  opticalHighPin: "33"  # Broche capteur optique niveau haut (bleu)
  auxPin1: "26"  # Broche auxiliaire 1 (bleu)
  auxPin2: "27"  # Broche auxiliaire 2 (jaune)
  dallasPin: "16"  # Broche pour capteur de température Dallas

  sdaPin: "21"  # Broche SDA (bus I2C)
  sclPin: "22"  # Broche SCL (bus I2C)

  # Adresses I2C des circuits EZO
  addPH: "99"  # Adresse circuit pH
  addEC: "100"  # Adresse circuit conductivité électrique (EC)
  addDO: "97"  # Adresse circuit oxygène dissous (DO)
  addRTD: "102"  # Adresse circuit RTD (température)
  addHUM: "111"  # Adresse circuit humidité
  addCO2: "105"  # Adresse circuit dioxyde de carbone (CO2)

  # Adresses circuits PMP (pompes)
  addPMP: "103"  # Pompe principale (blanc)
  addPMPWaste: "108"  # Pompe eau usée (rouge)
  addPMPClean: "109"  # Pompe eau propre (verte)
  addPMP_2: "110"  # Pompe auxiliaire 2 (orange)
  addPMP_3: "104"  # Pompe auxiliaire 3 (jaune)
  addPMP_4: "106"  # Pompe auxiliaire 4 (bleue)

  # Variables de calibration des températures
  cal_0: "0.0"  # Calibration à 0°C (glace)
  cal_100: "100.0"  # Calibration à 100°C (ébullition)
  cal_0_2: "0.0"  # Deuxième point de calibration à 0°C
  cal_100_2: "100.0"  # Deuxième point de calibration à 100°C

  # Intervalles de mise à jour des capteurs
  update_water: "60s"  # Niveau d'eau
  update_temp: "60s"  # Température
  update_ph: "60s"  # pH
  update_ec: "60s"  # Conductivité électrique
  update_button_ec: "60s"  # Bouton de lecture EC
  update_do: "60s"  # Oxygène dissous
  update_rtd: "60s"  # RTD (température)
  update_pmp: "60s"  # Pompes
  update_hum: "60s"  # Humidité
  update_button_hum: "60s"  # Bouton de lecture humidité
  update_co2: "60s"  # CO2
  update_button_co2: "60s"  # Bouton de lecture CO2
